export const headerLinks = [
  {
    label: "Home",
    route: "/",
  },
  {
    label: "Services",
    route: "/services",
  },
  {
    label: "About",
    route: "/about",
  },
  {
    label: "Contact",
    route: "/contact",
  },
];

export const counties = {
  Derbyshire: [
    "Alfreton",
    "Ashbourne",
    "Bakewell",
    "Belper",
    "Buxton",
    "Chesterfield",
    "Derby",
    "Dronfield",
    "Glossop",
    "Ilkeston",
    "Long Eaton",
    "Matlock",
    "Ripley",
    "Swadlincote",
  ],

  Herefordshire: [
    "Bromyard",
    "Hereford",
    "Kington",
    "Ledbury",
    "Leominster",
    "Ross-on-Wye",
  ],

  Leicestershire: [
    "Ashby-de-la-Zouch",
    "Coalville",
    "Hinckley",
    "Loughborough",
    "Market Harborough",
    "Melton Mowbray",
    "Oadby",
    "Wigston",
  ],

  Lincolnshire: [
    "Boston",
    "Bourne",
    "Grantham",
    "Gainsborough",
    "Lincoln",
    "Louth",
    "Market Deeping",
    "Skegness",
    "Spalding",
    "Stamford",
  ],

  Northamptonshire: [
    "Brackley",
    "Corby",
    "Daventry",
    "Desborough",
    "Kettering",
    "Northampton",
    "Peterborough",
    "Raunds",
    "Rushden",
    "Towcester",
    "Wellingborough",
  ],

  Nottinghamshire: [
    "Arnold",
    "Beeston",
    "Bingham",
    "Carlton",
    "Hucknall",
    "Mansfield",
    "Newark-on-Trent",
    "Nottingham",
    "Retford",
    "Southwell",
    "Worksop",
  ],

  Shropshire: [
    "Bishop's Castle",
    "Bridgnorth",
    "Church Stretton",
    "Craven Arms",
    "Ludlow",
    "Market Drayton",
    "Oswestry",
    "Shrewsbury",
    "Telford",
    "Wellington",
    "Whitchurch",
  ],

  Staffordshire: [
    "Burton upon Trent",
    "Cannock",
    "Cheadle",
    "Eccleshall",
    "Fazeley",
    "Hednesford",
    "Kidsgrove",
    "Leek",
    "Lichfield",
    "Newcastle-under-Lyme",
    "Rugeley",
    "Stafford",
    "Stoke-on-Trent",
    "Stone",
    "Tamworth",
    "Uttoxeter",
  ],
  Warwickshire: [
    "Kenilworth",
    "Leamington Spa",
    "Nuneaton",
    "Rugby",
    "Stratford-upon-Avon",
    "Warwick",
  ],
  "West Midlands": [
    "Birmingham",
    "Coventry",
    "Dudley",
    "Halesowen",
    "Oldbury",
    "Sandwell",
    "Solihull",
    "Stourbridge",
    "Sutton Coldfield",
    "Walsall",
    "West Bromwich",
    "Wolverhampton",
  ],
  Worcestershire: [
    "Alvechurch",
    "Badsey",
    "Belbroughton",
    "Bewdley",
    "Blakedown",
    "Bromsgrove",
    "Droitwich",
    "Evesham",
    "Hagley",
    "Hay-on-Wye",
    "Hockley Heath",
    "Kempsey",
    "Kidderminster",
    "Malvern",
    "Pebworth",
    "Redditch",
    "Rubery",
    "Stourport",
    "Tenbury",
    "Tredington",
    "Upton on Severn",
    "Welford on Avon",
    "Wolverley",
    "Worcester",
  ],
};
